version: '3.7'

services:
  auth-service:
    build:
      context: ./auth-service
    volumes:
      - ./auth-service:/usr/src/service/auth
      - /usr/src/service/auth/node_modules
    env_file: .config
    ports:
      - 3000:3000
    networks:
      - webnet
  
  user-service:
    build:
      context: ./user-service
    volumes:
      - ./user-service:/usr/src/service/user
      - /usr/src/service/user/node_modules
    env_file: .config
    ports:
      - 3001:3001
    networks:
      - webnet

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file: .mongo
    networks:
      - webnet
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file: .mongo-express
    networks:
      - webnet

networks:
  webnet: